P8105_hw2_yx2711
================
yx2711
2022-10-03

# Problem 1

Import the `NYC_Transit_Subway_Entrance_And_Exit_Data` data set and
change the variable type of route 8-11 to character type. Clean dataset
name using `janitor::clean_names()`. Use `ifelse` to convert `entry`
from character `YES` or `No` to logical variable type. The data is not
tidy yet. Its dimension is 20 columns and 1868 rows.

``` r
transit = 
  read_csv(
    "C:/Users/Carolinexyc/OneDrive/Desktop/P8105/p8105_hw2_yx2711/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))

nrow(transit)
```

    ## [1] 1868

``` r
ncol(transit)
```

    ## [1] 20

Uses `distinct` to obtain the number of distinct stations. There are 465
distinct stations.

``` r
transit %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

Use `filter()` to obtain the number of ADA compliant stations. There are
84 ADA compliant stations

``` r
transit %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

Use `filter()` to obtain the proportion of station entrances / exits
without vending allow entrance. There are 37.7% station station
entrances / exits without vending allow entrance.

``` r
transit %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

Use `pivot_longer()` to tidy data first. Then use `filter()` and
`distinct` to obtain the number of distinct station with A train and
with A train and are ADA compliant.

``` r
transit %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
transit %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

# Problem 2

Import `Trash Wheel Collection Data` - `Mr. Trash Wheel` and clean
names. Use `select()` to select dumpster-specific data and
`as.integer()`to convert the number of sports balls to integer. Add a
variable “sheet” using `mutate()`

``` r
mr_trash_wheel = read_xlsx("C:/Users/Carolinexyc/OneDrive/Desktop/P8105/p8105_hw2_yx2711/Trash Wheel Collection Data.xlsx", sheet = 1) %>% 
  janitor::clean_names() %>% 
  select(dumpster:homes_powered) %>% 
  mutate(
    sports_balls = as.integer(round(sports_balls, 0)),
    sheet = "Mr. Trash Wheel") %>% 
  drop_na(dumpster)
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
mr_trash_wheel
```

    ## # A tibble: 547 × 15
    ##    dumpster month year  date                weight_tons volume…¹ plast…² polys…³
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 537 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, sheet <chr>, and abbreviated
    ## #   variable names ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

Import `Trash Wheel Collection Data` - `Professor Trash Wheel` and clean
names. Use `select()` to select dumpster-specific data. Use `mutate()`
to change the year to a character type and add a variable “sheet”

``` r
professor_trash_wheel = read_xlsx("C:/Users/Carolinexyc/OneDrive/Desktop/P8105/p8105_hw2_yx2711/Trash Wheel Collection Data.xlsx", sheet = 2) %>% 
  janitor::clean_names() %>% 
  select(dumpster:homes_powered) %>% 
  mutate(
    sports_balls = as.integer(NA),
    year = as.character(year),
    sheet = "Professor Trash Wheel") %>% 
  drop_na(dumpster)

professor_trash_wheel
```

    ## # A tibble: 94 × 15
    ##    dumpster month    year  date                weight_…¹ volum…² plast…³ polys…⁴
    ##       <dbl> <chr>    <chr> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1        1 January  2017  2017-01-02 00:00:00      1.79      15    1950    6080
    ##  2        2 January  2017  2017-01-30 00:00:00      1.58      15    9540   11230
    ##  3        3 February 2017  2017-02-26 00:00:00      2.32      18    8350    9210
    ##  4        4 February 2017  2017-02-26 00:00:00      3.72      15    8590    1030
    ##  5        5 February 2017  2017-02-28 00:00:00      1.45      15    7830    9950
    ##  6        6 March    2017  2017-03-30 00:00:00      1.71      15    8210   10340
    ##  7        7 April    2017  2017-04-01 00:00:00      1.82      15    9830   11020
    ##  8        8 April    2017  2017-04-20 00:00:00      2.37      15    9240    8760
    ##  9        9 May      2017  2017-05-10 00:00:00      2.64      15    9540    8810
    ## 10       10 May      2017  2017-05-26 00:00:00      2.78      15    8230    7800
    ## # … with 84 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   homes_powered <dbl>, sports_balls <int>, sheet <chr>, and abbreviated
    ## #   variable names ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles,
    ## #   ⁴​polystyrene

Combine two datasets using `full_join()`

``` r
trash_wheel = bind_rows(mr_trash_wheel, professor_trash_wheel)

trash_wheel
```

    ## # A tibble: 641 × 15
    ##    dumpster month year  date                weight_tons volume…¹ plast…² polys…³
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 631 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, sheet <chr>, and abbreviated
    ## #   variable names ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

``` r
nrow(trash_wheel)
```

    ## [1] 641

``` r
ncol(trash_wheel)
```

    ## [1] 15

``` r
weight = filter(
  trash_wheel, sheet == "Professor Trash Wheel") %>% 
  pull(weight_tons) 

sport_ball = trash_wheel %>% 
 filter(sheet == "Mr. Trash Wheel" & year == "2020") %>% 
  pull(sports_balls)
```

The resulting dataset has 641 observations and 15 variables. Some
examples of key variables are weight, volume, plastic bottles,
polystyrene and so on. The total weight of trash collected by professor
trash wheel is 190.12 tons. The total number of sports balls collected
by Mr. Trash Wheel in 2020 is 856.

# Problem 3

Import `pols-month` dataset. Use `separate()` and `mutate()` to break up
variable month. Use `ifelse()` to create a president variable. Use
`select()` to drop variable.

``` r
pols_month = 
  read.csv("C:/Users/Carolinexyc/OneDrive/Desktop/P8105/p8105_hw2_yx2711/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day")) %>% 
  mutate(
    year = as.integer(year),
    month = month.name[as.integer(month)],
    day = as.integer(day),
    president = ifelse(prez_gop == 0, "dem", "gop" )
  ) %>% 
  select(-day, -prez_dem, -prez_gop)
```

Import `snp` dataset. Use `separate()` and `mutate()` to break up
variable month.

``` r
snp = 
  read.csv("C:/Users/Carolinexyc/OneDrive/Desktop/P8105/p8105_hw2_yx2711/fivethirtyeight_datasets/snp.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  separate(date, into = c("year","month", "day")) %>% 
   mutate(
    year = as.integer(year),
    year = ifelse(year > 2015, year - 100, year),
    month = month.name[as.integer(month)],
    day = as.integer(day),
  ) %>% 
  relocate(year, month) %>% 
  select(-day)
```

Import `unemployment` dataset Use `pivot_longer()` to convert the
dataset from wide to long format.

``` r
unemployment = 
  read.csv("C:/Users/Carolinexyc/OneDrive/Desktop/P8105/p8105_hw2_yx2711/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "Unemployed"
  ) %>% 
  mutate(
    month = str_to_title(month),
    month = month.name[match(month, month.abb)]
  )
```

Merge snp into pols

``` r
snp_pols =
  left_join(pols_month, snp)
```

    ## Joining, by = c("year", "month")

Merging unemployment into the result

``` r
result = 
  left_join(snp_pols, unemployment)
```

    ## Joining, by = c("year", "month")

``` r
nrow(result)
```

    ## [1] 822

``` r
ncol(result)
```

    ## [1] 11

``` r
max(result$year)
```

    ## [1] 2015

``` r
min(result$year)
```

    ## [1] 1947

The pols_month dataset contains in total 9 variables and 822
observations, and key variables are year, month, and president.  
The snp dataset contains 3 variables and 787 observations, and key
variables are year, month, and close. The unemployment dataset contains
3 variables and 816 observations, and key variables are year, month and
unemployment.  
The resulting dataset has 822 rows and 11 columns. The range of years is
from 1947 to 2015. The key variables are year, month, president, close,
and unemployment.
